"""Add Initial data

Revision ID: 0deb70febe07
Revises: 
Create Date: 2026-06-09 08:38:38.439453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0deb70febe07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nameahex_color',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nameahex_color_hex'), 'nameahex_color', ['hex'], unique=False)
    op.create_table('nameahex_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_version', sa.Integer(), nullable=False),
    sa.Column('password_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nameahex_user_username'), 'nameahex_user', ['username'], unique=True)
    op.create_table('nameahex_option',
    sa.Column('color_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['nameahex_color.id'], ),
    sa.PrimaryKeyConstraint('color_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nameahex_option')
    op.drop_index(op.f('ix_nameahex_user_username'), table_name='nameahex_user')
    op.drop_table('nameahex_user')
    op.drop_index(op.f('ix_nameahex_color_hex'), table_name='nameahex_color')
    op.drop_table('nameahex_color')
    # ### end Alembic commands ###
