"""Remove password salt

Revision ID: 57c1c738e1f0
Revises: 0deb70febe07
Create Date: 2026-06-09 12:27:44.069275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c1c738e1f0'
down_revision: Union[str, Sequence[str], None] = '0deb70febe07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nameahex_user', 'password_salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nameahex_user', sa.Column('password_salt', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
